language: rust

rust:
  - nightly

os:
  - linux

addons:
  apt:
    packages: qemu

before_script:
  - rustup component add rustfmt rust-src llvm-tools-preview
  - cargo install cargo-update cargo-xbuild bootimage
  - cargo install-update -a

script:
  - cargo xtest
  - bootimage build
  - cargo fmt -- --check

cache: cargo
